#!/usr/bin/perl
use strict; use warnings;

my $input = shift || 'book';

system( 'latex', "$input.tex" );
system( 'latex', "$input.tex" );

`dvips -f < $input.dvi > $input.ps`;
`ps2pdf - - < $input.ps > $input.pdf`;
