package JobAd::Model::position;
use strict; use warnings;

use base 'Gantry::Utils::DBIxClass', 'Exporter';

use JobAd::Model::GEN::position;

our $POSITION = 'JobAd::Model::position';

our @EXPORT_OK = ( '$POSITION' );

1;

=head1 NAME

JobAd::Model::position - model for position table (stub part)

=head1 DESCRIPTION

This model inherits from its generated helper, which inherits from
Gantry::Utils::DBIxClass.  It was generated by Bigtop, but is
NOT subject to regeneration.

=head1 METHODS (mixed in from JobAd::Model::GEN::position)

You may use all normal Gantry::Utils::DBIxClass methods and the
ones listed here:

=over 4

=item get_foreign_display_fields

=item get_foreign_tables

=item foreign_display

=item table_name

=back

=cut
