package JobAd::Model::skill;
use strict; use warnings;

use base 'Gantry::Utils::DBIxClass', 'Exporter';

use JobAd::Model::GEN::skill;

our $SKILL = 'JobAd::Model::skill';

our @EXPORT_OK = ( '$SKILL' );

1;

=head1 NAME

JobAd::Model::skill - model for skill table (stub part)

=head1 DESCRIPTION

This model inherits from its generated helper, which inherits from
Gantry::Utils::DBIxClass.  It was generated by Bigtop, but is
NOT subject to regeneration.

=head1 METHODS (mixed in from JobAd::Model::GEN::skill)

You may use all normal Gantry::Utils::DBIxClass methods and the
ones listed here:

=over 4

=item get_foreign_display_fields

=item get_foreign_tables

=item foreign_display

=item table_name

=back

=cut
